### PR TITLE
Add send_feature_report/get_feature_report support

### PR DESCRIPTION
**Pull request by wuest**
This adds an interface to `get_feature_report` and `send_feature_report`

The interface for `get_feature_report` is worth calling attention to.  As implemented, it closely mimics the API presented by other language HID interfaces - the returned value retains the report ID in the first byte, and the ByteString itself ends up 1 byte larger than the report length passed in (typically just to allow for a terminal `NUL`).

### CODE REVIEW

**Comment by chpatrick** [comment]
Thanks for the PR! I think it would be nicer though if the magic first byte was handled by the library though, rather than being implicit.

**Comment by wuest** [comment]
Sorry, I'm not quite sure what it is you want to change; can you explain a bit more what you're thinking, here?  I'm happy to tweak the PR.

**Comment by wuest** [comment]
Sorry to ping this issue, but I'll have some time tomorrow I'd love to devote to reaching parity with HID support available in other languages.

Looking over the PR, the only thing I can see as potentially being implicit is the return value from `getFeatureReport` being `ByteString` rather than something along the lines of `(ReportID, ByteString)`.

**Comment by chpatrick** [comment]
Yes, what I meant is that rather than having a `ByteString` with a special first byte it would be nice if it was a `(ReportID, ByteString)` instead.

**Comment by wuest** [comment]
No worries about the delay!  This update should cover it.

**Comment by chpatrick** [comment]
One more thing: you can use [`Data.ByteString.Internal.createAndTrim`](https://github.com/haskell/bytestring/blob/master/Data/ByteString/Internal.hs#L405) to create the `ByteString`, which means there's no intermediate Haskell list like with `peekArray`.

**Comment by wuest** [comment]
Hmm, I typically avoid calls to `Internal` functions if I can avoid it - I noted that `getSerialNumberString` also opted to manage memory inline.

If I move to using `createAndTrim`, that feels like asking you to take on a larger maintenance burden; since in practice calls to `getFeatureReport` tend to be relatively infrequent (usually providing a long-lived value or verifying the impact of `sendFeatureReport`) the potential for an additional `memcpy` seemed reasonable as a tradeoff.

If you still prefer calling into `Internal`, let me know and I'll update the code. :)

**Comment by wuest** [comment]
Nits are welcome!  While I care and will watch for issues with this library, it's still ultimately yours.

I'll update this over lunch.

**Pull request merged**
